-- liquibase formatted sql



-- changeset Zhandos:1742109228874-22
CREATE TABLE address
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state    VARCHAR(255),
    city     VARCHAR(255),
    street   VARCHAR(255),
    zip_code VARCHAR(255),
    country  VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

-- changeset Zhandos:1742109228874-23
ALTER TABLE cart_items
    ADD CONSTRAINT pk_cart_items PRIMARY KEY (cart_id, product_id);

-- changeset Zhandos:1742109228874-24
ALTER TABLE orders
    ADD CONSTRAINT pk_orders PRIMARY KEY (id);

-- changeset Zhandos:1742109228874-28
DROP TABLE product_images CASCADE;

-- changeset Zhandos:1742109228874-29
DROP TABLE product_tags CASCADE;

-- changeset Zhandos:1742109228874-30
ALTER TABLE carts
    DROP COLUMN created_at;
ALTER TABLE carts
    DROP COLUMN quantity;

-- changeset Zhandos:1742109228874-1
ALTER TABLE orders
    ALTER COLUMN address TYPE VARCHAR(255) USING (address::VARCHAR(255));

-- changeset Zhandos:1742109228874-2
ALTER TABLE products
    ALTER COLUMN category TYPE VARCHAR(255) USING (category::VARCHAR(255));

-- changeset Zhandos:1742109228874-3
ALTER TABLE users
    DROP COLUMN created_on;

-- changeset Zhandos:1742109228874-4
ALTER TABLE users
    ADD created_on date;

-- changeset Zhandos:1742109228874-5
ALTER TABLE products
    ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

-- changeset Zhandos:1742109228874-6
ALTER TABLE products
    DROP COLUMN id;
ALTER TABLE products
    DROP COLUMN price;

-- changeset Zhandos:1742109228874-7
ALTER TABLE products
    ADD id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

-- changeset Zhandos:1742109228874-8
ALTER TABLE products
    ALTER COLUMN name DROP NOT NULL;

-- changeset Zhandos:1742109228874-9
ALTER TABLE products
    ALTER COLUMN owner_id DROP NOT NULL;

-- changeset Zhandos:1742109228874-10
ALTER TABLE users
    ALTER COLUMN password TYPE VARCHAR(255) USING (password::VARCHAR(255));

-- changeset Zhandos:1742109228874-11
ALTER TABLE users
    ALTER COLUMN password DROP NOT NULL;

-- changeset Zhandos:1742109228874-12
ALTER TABLE users
    ALTER COLUMN phone_number TYPE VARCHAR(255) USING (phone_number::VARCHAR(255));

-- changeset Zhandos:1742109228874-13
ALTER TABLE users
    ALTER COLUMN phone_number DROP NOT NULL;

-- changeset Zhandos:1742109228874-15
ALTER TABLE products
    ADD price FLOAT;

-- changeset Zhandos:1742109228874-16
ALTER TABLE products
    ALTER COLUMN price DROP NOT NULL;

-- changeset Zhandos:1742109228874-17
ALTER TABLE cart_items
    DROP COLUMN product_id;

-- changeset Zhandos:1742109228874-18
ALTER TABLE cart_items
    ADD product_id INTEGER NOT NULL PRIMARY KEY;
ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

-- changeset Zhandos:1742109228874-19
ALTER TABLE users
    ALTER COLUMN profile_image TYPE VARCHAR(255) USING (profile_image::VARCHAR(255));

-- changeset Zhandos:1742109228874-20
ALTER TABLE users
    ALTER COLUMN username TYPE VARCHAR(255) USING (username::VARCHAR(255));

-- changeset Zhandos:1742109228874-21
ALTER TABLE users
    ALTER COLUMN username DROP NOT NULL;

