package com.jzargo.shared.common;

public enum Tags {
    NEW, DISCOUNT, TRENDING, POPULAR, LIMITED_EDITION, ECO_FRIENDLY,
    HANDMADE, ORGANIC, BESTSELLER, HIGH_QUALITY, LUXURY, BUDGET,
    IMPORTED, LOCAL, SEASONAL, CLEARANCE, EXCLUSIVE, FAST_SHIPPING,
    GIFT_IDEA, CUSTOMIZABLE
}
