package com.jzargo.common;

public enum Categories {
    ELECTRONICS, CLOTHING, FOOD, BOOKS, HOME_APPLIANCES, TOYS,
    SPORTS, BEAUTY, HEALTH, AUTOMOTIVE, PET_SUPPLIES, OFFICE_SUPPLIES,
    JEWELRY, FURNITURE, MUSIC, VIDEO_GAMES, GARDENING, ART, BABY_PRODUCTS
}
